print("Reglas tres en raya")
print("1. El juego se juega en un tablero de 3x3")
print("2. Los jugadores eligen un símbolo para jugar")
print("3. Inicia el jugador X")
print("4. Continua el jugador O y así sucesivamente")
print("5. No se puede jugar en una casilla ocupada")
print("6. Gana el jugador que logre alinear tres símbolos en línea horizontal, vertical o diagonal")
print("7. Si no hay más casillas disponibles y no hay ganador es empate")